### ISSUE TITLE
Try using gelu approximate = 'tanh'

### ISSUE THREAD

**Issue by drisspg** [karpathy/nanoGPT#2]
## Suggestion

I noticed that you are defining a fused GELU similar to the one used in the Google BERT repository. As a tip, the [GELU](https://pytorch.org/docs/stable/generated/torch.nn.GELU.html). function in PyTorch has an optional `approximate `argument that you can set to `tanh` which should give you equivalent results but with slightly better efficiency. I'm not sure if using this option would go against the spirit of your project, but I just wanted to let you know about it.

Regardless, I think your ability to extract useful insights from complex systems is impressive and inspiring!

**Comment by karpathy** [comment]
Thank you, that's interesting. I took that line directly out of openai gpt2 code, so I'm worried that changing it would make the pretrained weights from their checkpoints not give the correct results. In order to preserve the ability to init from these checkpoints I will try to not mess with it too much.

**Comment by drisspg** [comment]
Makes sense 👍
