### ISSUE TITLE
MFU calculation

### ISSUE THREAD

**Issue by Hannibal046** [karpathy/nanoGPT#322]
Hi, maybe we should exclude the parameters of `Self Attention` here for `6N`? Since `6N` is only for feedforward layer calculation.

https://github.com/karpathy/nanoGPT/blob/eba36e84649f3c6d840a93092cb779a260544d08/model.py#L289-L303

![image](https://github.com/karpathy/nanoGPT/assets/38466901/ed3b0313-6c2a-4960-8b39-01131e83289b)

**Comment by shehper** [comment]
@Hannibal046, 6N is not for feedforward layer. 6N is the total amount of FLOPs we expect for forward pass + backward pass through a decoder-only Transformer  if we do not consider the FLOPs needed for masking attention computation. See equation 2.2 and Table 1 in [Kaplan et al](https://arxiv.org/pdf/2001.08361.pdf). 

Note that they have 2N + ... instead of 6N + ... because they are writing down the result for forward pass only. Backward pass requires twice as many FLOPs, hence we get 6N + ... for a combination of forward-backward pass.

**Comment by Hannibal046** [comment]
@shehper Thanks so much for the clarification!
