### ISSUE TITLE
Conversational training

### ISSUE THREAD

**Issue by VatsaDev** [karpathy/nanoGPT#328]
As far I as I understand the model, its text generation based, so can we train it for a conversation basis like this?

```
User: <utterance>
Assistant: <utterance>
User: <utterance>
Assistant: <utterance>
...
```

**Comment by curvednebula** [comment]
I think this is a very good question! I.e. it is good to know how to train the model on question - answer pairs. What I don't understand yet is that I'm not sure if model need to learn to predict tokens in the question, but tokens in answer only. While if we pass question and answer and one input to GPT - my understanding is that it will learn to predict both - question part and answer part - because for the model it is one sequence of tokens.

**Comment by VatsaDev** [comment]
a question answer pair model would probably better be left to question anwser from context model, I took my example above from redpajama chat 3b

**Comment by VatsaDev** [comment]
i would probably use a database like [chat arena conversations](https://huggingface.co/datasets/lmsys/chatbot_arena_conversations/viewer/lmsys--chatbot_arena_conversations/train?row=1) along with adding a stop at token function
